---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-uptime-uptime-com-v1alpha1-monitor
  failurePolicy: Fail
  name: vmonitor.kb.io
  rules:
  - apiGroups:
    - uptime.uptime.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - monitors
  sideEffects: None
